FROM postgres:10
COPY /scripts/*.sql /docker-entrypoint-initdb.d/
ADD scripts/01_init.sql /docker-entrypoint-initdb.d
ADD scripts/02_data.sql /docker-entrypoint-initdb.d
RUN chmod a+r /docker-entrypoint-initdb.d/*
EXPOSE 6543