version: '3.8'
services:
  db:
    image: postgres:10
    environment:
      POSTGRES_DB: timetravelmovies
      POSTGRES_USER: timetraveller
      POSTGRES_PASSWORD: itaintpossible
    ports:
      - "5432:5432"
    expose:
      - "6543"
    restart: unless-stopped
