version: '3.8'
services:
  db:
    container_name: ttdb
    environment:
      POSTGRES_DB: timetravelmovies
      POSTGRES_USER: timetraveller
      POSTGRES_PASSWORD: itaintpossible
    ports:
      - "5432:5432"
    expose:
      - "6543"
    volumes:
      - ./data:/data
    restart: unless-stopped
